# Generated by Django 3.1.5 on 2021-01-14 08:51

import capone.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerbalance',
            name='related_object_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(default=capone.models.get_or_create_manual_transaction_type_id, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capone.transactiontype'),
        ),
        migrations.AlterField(
            model_name='transactionrelatedobject',
            name='related_object_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
