# Generated by Django 3.1.5 on 2021-02-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capone', '0003_drop_ledger_name_uniqueness_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='number',
            field=models.PositiveIntegerField(help_text='Unique numeric identifier for this ledger', null=True, unique=True),
        ),
    ]
